import { describe, expect, it } from 'vitest';
import { randomUUID } from 'node:crypto';
import { openDatabase } from '../../database/client';
import { applyMigrations } from '../../database/migrate';
import { SqliteFulfillmentMutationRepository } from './sqliteDomainRepository';
import { FulfillmentApplicationService } from './service';

function fixture() {
  const db = openDatabase(); applyMigrations(db);
  const customerId=randomUUID(), orderId=randomUUID(), purchaseId=randomUUID(), attemptId=randomUUID(), teaId=randomUUID(), lotId=randomUUID(); const now=new Date().toISOString();
  db.prepare('INSERT INTO customers (id,email,created_at) VALUES (?,?,?)').run(customerId,`${customerId}@test.local`,now);
  db.prepare('INSERT INTO tea_families (id,name) VALUES (?,?)').run(`family-${teaId}`,'Test Family');
  db.prepare(`INSERT INTO teas (id,slug,name,family_id,sensory_json,discovery_distance,price_amount,price_currency,pack_size_grams,supply_status,provenance_confidence,publishing_state,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(teaId,`tea-${teaId}`,'Test Tea',`family-${teaId}`,'{}',50,100,'UAH',10,'available','verified','published',now,now);
  db.prepare(`INSERT INTO tea_lots (id,tea_id,lot_code,inventory_quantity,supply_status,created_at,updated_at) VALUES (?,?,?,?,?,?,?)`).run(lotId,teaId,`LOT-${lotId}`,10,'available',now,now);
  const itemId=randomUUID(); const shipping={recipientName:'Test',addressLine1:'1 Main',city:'Dnipro',postalCode:'49000',countryCode:'UA'};
  db.prepare(`INSERT INTO orders (id,customer_id,status,currency,subtotal_amount,discount_amount,shipping_amount,total_amount,shipping_snapshot_json,idempotency_key,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)`).run(orderId,customerId,'confirmed','UAH',200,0,0,200,JSON.stringify(shipping),randomUUID(),now,now);
  db.prepare(`INSERT INTO order_items (id,order_id,sku,tea_id,tea_name_snapshot,quantity,unit_price_amount,unit_price_currency,line_total_amount,recommendation_history_id,discovery_box_snapshot_json) VALUES (?,?,?,?,?,?,?,?,?,?,?)`).run(itemId,orderId,'TEA-TEST',teaId,'Test Tea',2,100,'UAH',200,null,null);
  db.prepare(`INSERT INTO payment_attempts (id,order_id,customer_id,provider,merchant_reference,requested_amount,requested_currency,state,idempotency_key,created_at,updated_at,confirmed_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)`).run(attemptId,orderId,customerId,'MONO',`ref-${attemptId}`,200,'UAH','SUCCEEDED',randomUUID(),now,now,now);
  db.prepare(`INSERT INTO purchases (id,order_id,customer_id,amount,currency,confirmed_at,payment_attempt_id,provider,provider_invoice_id,provider_reference) VALUES (?,?,?,?,?,?,?,?,?,?)`).run(purchaseId,orderId,customerId,200,'UAH',now,attemptId,'MONO',`inv-${purchaseId}`,`ref-${purchaseId}`);
  return {db,service:new FulfillmentApplicationService(new SqliteFulfillmentMutationRepository(db)),customerId,orderId,purchaseId,teaId,lotId,itemId};
}
function boxFixture(){const f=fixture();f.db.prepare('UPDATE tea_lots SET inventory_quantity=20 WHERE id=?').run(f.lotId);const items=['MATCH','MATCH','MATCH','STRETCH','STRETCH','WILDCARD'].map((classification,i)=>({teaId:f.teaId,teaName:'Test Tea',classification,position:i+1,score:80-i,reasons:['reason']}));f.db.prepare('UPDATE order_items SET sku=?, discovery_box_snapshot_json=? WHERE id=?').run('DISCOVERY-BOX',JSON.stringify({discoveryBoxId:randomUUID(),algorithmVersion:'recommendation-v1',selectionVersion:'discovery-box-v1',items}),f.itemId);return f;}

describe('F2 fulfillment application',()=>{
  it('creates once from confirmed Purchase with immutable snapshots and provenance',()=>{const f=fixture();const a=f.service.createFulfillmentFromPurchase(f.purchaseId);const b=f.service.createFulfillmentFromPurchase(f.purchaseId);expect(a.id).toBe(b.id);expect(a.status).toBe('PENDING');expect(JSON.parse(a.shippingSnapshotJson).city).toBe('Dnipro');expect(f.db.prepare('SELECT COUNT(*) c FROM fulfillments').get()).toEqual({c:1});expect(f.db.prepare('SELECT COUNT(*) c FROM fulfillment_items').get()).toEqual({c:1});f.db.close();});
  it('rejects missing Purchase, non-confirmed Order and unsuccessful PaymentAttempt',()=>{const f=fixture();expect(()=>f.service.createFulfillmentFromPurchase(randomUUID())).toThrow();f.db.prepare("UPDATE orders SET status='created' WHERE id=?").run(f.orderId);expect(()=>f.service.createFulfillmentFromPurchase(f.purchaseId)).toThrow();f.db.prepare("UPDATE orders SET status='confirmed' WHERE id=?").run(f.orderId);f.db.prepare("UPDATE payment_attempts SET state='DECLINED' WHERE order_id=?").run(f.orderId);expect(()=>f.service.createFulfillmentFromPurchase(f.purchaseId)).toThrow();f.db.close();});
  it('allocates exact stock atomically on READY and never makes inventory negative',()=>{const f=fixture();const x=f.service.createFulfillmentFromPurchase(f.purchaseId);const r=f.service.markReady(x.id,'SYSTEM','ready-1');expect(r.status).toBe('READY');expect((f.db.prepare('SELECT inventory_quantity q FROM tea_lots WHERE id=?').get(f.lotId) as {q:number}).q).toBe(8);expect(f.db.prepare('SELECT COUNT(*) c FROM inventory_allocations WHERE fulfillment_item_id=(SELECT id FROM fulfillment_items WHERE fulfillment_id=?)').get(x.id)).toEqual({c:1});f.db.close();});
  it('rolls back a failed allocation with no partial writes',()=>{const f=fixture();f.db.prepare('UPDATE tea_lots SET inventory_quantity=1 WHERE id=?').run(f.lotId);const x=f.service.createFulfillmentFromPurchase(f.purchaseId);expect(()=>f.service.markReady(x.id,'SYSTEM','ready-1')).toThrow();expect(f.service.getFulfillment(x.id).status).toBe('PENDING');expect((f.db.prepare('SELECT inventory_quantity q FROM tea_lots WHERE id=?').get(f.lotId) as {q:number}).q).toBe(1);expect(f.db.prepare('SELECT COUNT(*) c FROM inventory_allocations').get()).toEqual({c:0});f.db.close();});
  it('consumes reserved allocations exactly once at PACKED',()=>{const f=fixture();const x=f.service.createFulfillmentFromPurchase(f.purchaseId);f.service.markReady(x.id,'SYSTEM','ready');f.service.startPacking(x.id,'YUNELA:operator','pack-start');expect(f.service.markPacked(x.id,'YUNELA:operator','pack').status).toBe('PACKED');expect(f.db.prepare("SELECT status FROM inventory_allocations WHERE fulfillment_item_id=(SELECT id FROM fulfillment_items WHERE fulfillment_id=?)").get(x.id)).toEqual({status:'CONSUMED'});expect(f.db.prepare("SELECT COUNT(*) c FROM inventory_allocations WHERE status='CONSUMED'").get()).toEqual({c:1});expect(f.service.markPacked(x.id,'YUNELA:operator','pack-duplicate').status).toBe('PACKED');f.db.close();});
  it('releases reserved inventory on cancellation and cannot release consumed stock',()=>{const f=fixture();const x=f.service.createFulfillmentFromPurchase(f.purchaseId);f.service.markReady(x.id,'SYSTEM','ready');f.service.cancelFulfillment(x.id,'YUNELA:operator','cancelled','cancel');expect((f.db.prepare('SELECT inventory_quantity q FROM tea_lots WHERE id=?').get(f.lotId) as {q:number}).q).toBe(10);expect(f.db.prepare("SELECT status FROM inventory_allocations WHERE fulfillment_item_id=(SELECT id FROM fulfillment_items WHERE fulfillment_id=?)").get(x.id)).toEqual({status:'RELEASED'});f.db.close();});
  it('enforces main lifecycle, shipment creation ordering and terminal protection',()=>{const f=fixture();const x=f.service.createFulfillmentFromPurchase(f.purchaseId);expect(()=>f.service.markPacked(x.id,'YUNELA:o','bad')).toThrow();f.service.markReady(x.id,'SYSTEM','r');f.service.startPacking(x.id,'YUNELA:o','p');f.service.markPacked(x.id,'YUNELA:o','k');expect(()=>f.service.markDelivered(x.id,'YUNELA:o','d')).toThrow();expect(f.service.createShipment(x.id,'YUNELA:o','s').status).toBe('CREATED');f.service.markShipped(x.id,'YUNELA:o','ship');f.service.markDelivered(x.id,'YUNELA:o','deliver');expect(f.service.getFulfillment(x.id).status).toBe('DELIVERED');expect(()=>f.service.markReady(x.id,'SYSTEM','late')).toThrow();f.db.close();});
  it('requires YUNELA authority for shipment handoff',()=>{const f=fixture();const x=f.service.createFulfillmentFromPurchase(f.purchaseId);f.service.markReady(x.id,'SYSTEM','r');f.service.startPacking(x.id,'SUPPLIER:one','p');f.service.markPacked(x.id,'SUPPLIER:one','k');f.service.createShipment(x.id,'SUPPLIER:one','s');expect(()=>f.service.markShipped(x.id,'SUPPLIER:one','ship')).toThrow();f.db.close();});
  it('keeps one Shipment per Fulfillment and creation idempotent',()=>{const f=fixture();const x=f.service.createFulfillmentFromPurchase(f.purchaseId);f.service.markReady(x.id,'SYSTEM','r');f.service.startPacking(x.id,'YUNELA:o','p');f.service.markPacked(x.id,'YUNELA:o','k');const a=f.service.createShipment(x.id,'YUNELA:o','s');const b=f.service.createShipment(x.id,'YUNELA:o','s2');expect(a.id).toBe(b.id);expect(f.db.prepare('SELECT COUNT(*) c FROM shipments WHERE fulfillment_id=?').get(x.id)).toEqual({c:1});f.db.close();});
  it('keeps Purchase and PaymentAttempt untouched by fulfillment exceptions',()=>{const f=fixture();const x=f.service.createFulfillmentFromPurchase(f.purchaseId);f.service.markFailed(x.id,'YUNELA:o','supplier failure','fail');expect(f.db.prepare('SELECT state FROM payment_attempts WHERE id=(SELECT payment_attempt_id FROM purchases WHERE id=?)').get(f.purchaseId)).toEqual({state:'SUCCEEDED'});expect(f.db.prepare('SELECT COUNT(*) c FROM purchases WHERE id=?').get(f.purchaseId)).toEqual({c:1});f.db.close();});
  it('supports LOST after shipment and RETURNED only after physical movement',()=>{const f=fixture();const x=f.service.createFulfillmentFromPurchase(f.purchaseId);f.service.markReady(x.id,'SYSTEM','r');f.service.startPacking(x.id,'YUNELA:o','p');f.service.markPacked(x.id,'YUNELA:o','k');f.service.createShipment(x.id,'YUNELA:o','s');f.service.markShipped(x.id,'YUNELA:o','sh');f.service.markLost(x.id,'YUNELA:o','lost','lost');expect(f.service.getFulfillment(x.id).status).toBe('LOST');const g=fixture();const y=g.service.createFulfillmentFromPurchase(g.purchaseId);g.service.markReady(y.id,'SYSTEM','r');g.service.startPacking(y.id,'YUNELA:o','p');g.service.markPacked(y.id,'YUNELA:o','k');g.service.createShipment(y.id,'YUNELA:o','s');g.service.markShipped(y.id,'YUNELA:o','sh');g.service.markDelivered(y.id,'YUNELA:o','d');g.service.recordReturn(y.id,'YUNELA:o','manual return','ret');expect(g.service.getFulfillment(y.id).status).toBe('RETURNED');f.db.close();g.db.close();});
  it('requires explicit Discovery Box approval and preserves the commercial snapshot',()=>{const f=boxFixture();const before=(f.db.prepare('SELECT discovery_box_snapshot_json v FROM order_items WHERE id=?').get(f.itemId) as {v:string}).v;const x=f.service.createFulfillmentFromPurchase(f.purchaseId);f.service.handleDiscoveryBoxShortage(x.id,{originalTeaId:f.teaId,reason:'lot unavailable'},'YUNELA:o','shortage');expect(f.service.getFulfillment(x.id).status).toBe('PENDING_CUSTOMER_APPROVAL');f.service.recordCustomerApproval(x.id,{originalTeaId:f.teaId,replacementTeaId:f.teaId,reason:'approved replacement',actor:'YUNELA:o',customerDecision:'APPROVED',timestamp:new Date().toISOString()},'approval');const after=(f.db.prepare('SELECT discovery_box_snapshot_json v FROM order_items WHERE id=?').get(f.itemId) as {v:string}).v;expect(after).toBe(before);expect(f.service.markReady(x.id,'SYSTEM','ready-after-approval').status).toBe('READY');f.db.close();});
  it('preserves six-component Box provenance and replacement audit',()=>{const f=boxFixture();const x=f.service.createFulfillmentFromPurchase(f.purchaseId);expect(JSON.parse(x.itemsSnapshotJson)[0].discoveryBoxSnapshot.items).toHaveLength(6);f.service.handleDiscoveryBoxShortage(x.id,{originalTeaId:f.teaId,originalLotId:f.lotId,reason:'shortage'},'YUNELA:o','short');f.service.recordCustomerApproval(x.id,{originalTeaId:f.teaId,originalLotId:f.lotId,replacementTeaId:f.teaId,replacementLotId:f.lotId,reason:'approved',actor:'YUNELA:o',customerDecision:'APPROVED',timestamp:new Date().toISOString()},'approve');const events=f.db.prepare('SELECT event_type eventType FROM fulfillment_events WHERE fulfillment_id=?').all(x.id) as Array<{eventType:string}>;expect(events.some(e=>e.eventType.includes('originalLotId')&&e.eventType.includes('replacementLotId'))).toBe(true);f.db.close();});
  it('serializes competing READY operations so allocation occurs once',async()=>{const f=fixture();const x=f.service.createFulfillmentFromPurchase(f.purchaseId);const results=await Promise.allSettled([Promise.resolve().then(()=>f.service.markReady(x.id,'SYSTEM','r1')),Promise.resolve().then(()=>f.service.markReady(x.id,'SYSTEM','r2'))]);expect(results.filter(r=>r.status==='fulfilled')).toHaveLength(1);expect(f.service.getFulfillment(x.id).status).toBe('READY');expect((f.db.prepare('SELECT inventory_quantity q FROM tea_lots WHERE id=?').get(f.lotId) as {q:number}).q).toBe(8);f.db.close();});
});
