import { randomUUID } from 'node:crypto';
import { ApplicationError } from '../errors';
import type { OrderItemSnapshot } from '../../contracts/commerce';
import { assertDiscoveryBoxComposition, assertFulfillmentTransition, FulfillmentDomainError, type FulfillmentStatus, type ShipmentStatus } from '../../domain/fulfillment';
import type { FulfillmentRecord, FulfillmentItemRecord, ShipmentRecord, FulfillmentEventRecord } from './repositories';
import type { FulfillmentMutationRepository } from './sqliteDomainRepository';

export interface ReplacementApproval {
  originalTeaId: string; originalLotId?: string; replacementTeaId: string; replacementLotId?: string;
  reason: string; actor: string; customerDecision: 'APPROVED' | 'REJECTED'; timestamp: string;
}
function domainGuard(fn: () => void): void { try { fn(); } catch (error) { if (error instanceof FulfillmentDomainError) throw new ApplicationError('DOMAIN_RULE_VIOLATION', error.message); throw error; } }
function now() { return new Date().toISOString(); }
function eventKey(fulfillmentId:string, operationKey:string) { return `${fulfillmentId}:${operationKey}`; }
function snapshotItem(item: OrderItemSnapshot) { return JSON.stringify(item); }
function provenance(item: OrderItemSnapshot) { return JSON.stringify({ teaId:item.teaId, recommendationHistoryId:item.recommendationHistoryId, discoveryBoxSnapshot:item.discoveryBoxSnapshot }); }

export class FulfillmentApplicationService {
  constructor(private readonly repo: FulfillmentMutationRepository) {}
  createFulfillmentFromPurchase(purchaseId: string, operationKey = `create:${purchaseId}`): FulfillmentRecord {
    return this.repo.transaction(() => {
      const context = this.repo.getPurchaseContext(purchaseId); if (!context) throw new ApplicationError('NOT_FOUND', `Authoritative Purchase ${purchaseId} or successful PaymentAttempt was not found`);
      const existing = this.repo.getFulfillmentByPurchaseId(purchaseId); if (existing) return existing;
      const { purchase, order, paymentAttempt } = context;
      if (order.status !== 'confirmed') throw new ApplicationError('DOMAIN_RULE_VIOLATION', 'Fulfillment requires a CONFIRMED Order');
      if (purchase.orderId !== order.id || purchase.customerId !== order.customerId || paymentAttempt.orderId !== order.id || paymentAttempt.customerId !== order.customerId || paymentAttempt.state !== 'SUCCEEDED') throw new ApplicationError('PURCHASE_NOT_AUTHORIZED', 'Purchase, Order and successful PaymentAttempt ownership does not match');
      if (!order.items.length) throw new ApplicationError('DOMAIN_RULE_VIOLATION', 'Fulfillment requires at least one OrderItem');
      for (const item of order.items) if (item.discoveryBoxSnapshot) domainGuard(() => assertDiscoveryBoxComposition(item.discoveryBoxSnapshot!.items));
      const timestamp = now();
      const record: FulfillmentRecord = { id: randomUUID(), orderId:order.id, purchaseId:purchase.id, customerId:order.customerId, status:'PENDING', shippingSnapshotJson:JSON.stringify(order.shipping), itemsSnapshotJson:JSON.stringify(order.items), createdAt:timestamp, updatedAt:timestamp };
      this.repo.createFulfillment(record);
      for (const item of order.items) { const fi: FulfillmentItemRecord = { id:randomUUID(), fulfillmentId:record.id, orderItemId:item.id, sku:item.sku, quantity:item.quantity, productSnapshotJson:snapshotItem(item), provenanceReference:provenance(item), allocationStatus:'PENDING', createdAt:timestamp, updatedAt:timestamp }; this.repo.createFulfillmentItem(fi); }
      this.repo.appendFulfillmentEvent(this.event(record.id,'FULFILLMENT_CREATED',undefined,'PENDING','SYSTEM',operationKey,timestamp));
      return record;
    });
  }
  getFulfillment(id:string) { const f=this.repo.getFulfillmentById(id); if(!f) throw new ApplicationError('NOT_FOUND',`Fulfillment ${id} was not found`); return f; }
  transitionFulfillment(id:string, to:FulfillmentStatus, actor:string, operationKey:string): FulfillmentRecord {
    return this.repo.transaction(() => { const current=this.require(id); const key=eventKey(id,operationKey); if(this.repo.listFulfillmentEvents(id).some(e=>e.eventKey===key)) return current; if(current.status===to)return current; domainGuard(()=>assertFulfillmentTransition(current.status,to)); if(to==='READY')this.makeReady(current); if(to==='PACKED')this.consume(current); if(to==='SHIPPED'&&!this.repo.getShipmentByFulfillmentId(id))throw new ApplicationError('DOMAIN_RULE_VIOLATION','Fulfillment cannot be shipped before Shipment exists'); if(to==='CANCELLED'||(to==='FAILED'&&['READY','PACKING','PENDING_CUSTOMER_APPROVAL'].includes(current.status)))this.release(current); if(!this.repo.setFulfillmentStatus(id,current.status,to,now()))throw new ApplicationError('CONFLICT','Fulfillment changed concurrently; retry with a fresh operation'); const result=this.require(id); this.repo.appendFulfillmentEvent(this.event(id,`STATE:${current.status}->${to}`,current.status,to,actor,operationKey,result.updatedAt)); return result; });
  }
  validateReadiness(id:string){return this.repo.transaction(()=>this.readiness(this.require(id)));}
  markReady(id:string,actor:string,operationKey:string){return this.transitionFulfillment(id,'READY',actor,operationKey);}
  startPacking(id:string,actor:string,operationKey:string){this.requireActor(actor);return this.transitionFulfillment(id,'PACKING',actor,operationKey);}
  markPacked(id:string,actor:string,operationKey:string){this.requireActor(actor);return this.transitionFulfillment(id,'PACKED',actor,operationKey);}
  markShipped(id:string,actor:string,operationKey:string){this.requireYunela(actor);return this.repo.transaction(()=>{const f=this.require(id);const key=eventKey(id,operationKey);if(this.repo.listFulfillmentEvents(id).some(e=>e.eventKey===key))return f;domainGuard(()=>assertFulfillmentTransition(f.status,'SHIPPED'));const s=this.repo.getShipmentByFulfillmentId(id);if(!s)throw new ApplicationError('DOMAIN_RULE_VIOLATION','Shipment must exist before SHIPPED');const shipmentStatus=s.status as ShipmentStatus;if(shipmentStatus==='CREATED'){if(!this.repo.updateShipmentStatus(s.id,shipmentStatus,'SHIPPED',now()))throw new ApplicationError('CONFLICT','Shipment changed concurrently');}else if(shipmentStatus!=='SHIPPED')throw new ApplicationError('DOMAIN_RULE_VIOLATION',`Shipment is ${shipmentStatus}`);const ts=now();if(!this.repo.setFulfillmentStatus(id,f.status,'SHIPPED',ts))throw new ApplicationError('CONFLICT','Fulfillment changed concurrently');const result=this.require(id);this.repo.appendFulfillmentEvent(this.event(id,'STATE:PACKED->SHIPPED',f.status,'SHIPPED',actor,operationKey,ts));return result;});}
  markDelivered(id:string,actor:string,operationKey:string){this.requireYunela(actor);return this.repo.transaction(()=>{const f=this.require(id);const key=eventKey(id,operationKey);if(this.repo.listFulfillmentEvents(id).some(e=>e.eventKey===key))return f;domainGuard(()=>assertFulfillmentTransition(f.status,'DELIVERED'));const s=this.repo.getShipmentByFulfillmentId(id);if(!s||s.status!=='SHIPPED')throw new ApplicationError('DOMAIN_RULE_VIOLATION','Shipment must be SHIPPED before delivery');if(!this.repo.updateShipmentStatus(s.id,'SHIPPED','DELIVERED',now()))throw new ApplicationError('CONFLICT','Shipment changed concurrently');const ts=now();if(!this.repo.setFulfillmentStatus(id,f.status,'DELIVERED',ts))throw new ApplicationError('CONFLICT','Fulfillment changed concurrently');const result=this.require(id);this.repo.appendFulfillmentEvent(this.event(id,'STATE:SHIPPED->DELIVERED',f.status,'DELIVERED',actor,operationKey,ts));return result;});}
  markFailed(id:string,actor:string,reason:string,operationKey:string){return this.exception(id,'FAILED',actor,reason,operationKey);}
  markLost(id:string,actor:string,reason:string,operationKey:string){return this.exception(id,'LOST',actor,reason,operationKey);}
  cancelFulfillment(id:string,actor:string,reason:string,operationKey:string){return this.exception(id,'CANCELLED',actor,reason,operationKey);}
  recordReturn(id:string,actor:string,reason:string,operationKey:string){return this.exception(id,'RETURNED',actor,reason,operationKey);}
  createShipment(id:string,actor:string,operationKey:string,input:{carrier?:string;trackingNumber?:string;trackingUrl?:string}={}){return this.repo.transaction(()=>{const f=this.require(id);if(f.status!=='PACKED')throw new ApplicationError('DOMAIN_RULE_VIOLATION','Shipment can only be created after PACKED');const existing=this.repo.getShipmentByFulfillmentId(id);if(existing)return existing;const ts=now();const s:ShipmentRecord={id:randomUUID(),fulfillmentId:id,status:'CREATED',...(input.carrier?{carrier:input.carrier}:{}),...(input.trackingNumber?{trackingNumber:input.trackingNumber}:{}),...(input.trackingUrl?{trackingUrl:input.trackingUrl}:{}),createdAt:ts,updatedAt:ts};this.repo.createShipment(s);this.repo.appendFulfillmentEvent(this.event(id,'SHIPMENT_CREATED',f.status,f.status,actor,operationKey,ts));return s;});}
  transitionShipment(id:string,to:ShipmentStatus,actor:string,operationKey:string):ShipmentRecord{return this.repo.transaction(()=>{const f=this.require(id);const s=this.repo.getShipmentByFulfillmentId(id);if(!s)throw new ApplicationError('NOT_FOUND','Shipment was not created');const key=eventKey(id,`SHIPMENT:${operationKey}`);if(this.repo.listFulfillmentEvents(id).some(e=>e.eventKey===key))return s;const shipmentStatus=s.status as ShipmentStatus;if(shipmentStatus===to)return s;const allowed:Record<ShipmentStatus,ShipmentStatus[]>={CREATED:['SHIPPED'],SHIPPED:['DELIVERED','FAILED','LOST','RETURNED'],DELIVERED:['RETURNED'],FAILED:[],LOST:[],RETURNED:[]};if(!allowed[shipmentStatus].includes(to))throw new ApplicationError('DOMAIN_RULE_VIOLATION',`Shipment cannot transition from ${shipmentStatus} to ${to}`);if(to==='SHIPPED')this.requireYunela(actor);if(!this.repo.updateShipmentStatus(s.id,shipmentStatus,to,now()))throw new ApplicationError('CONFLICT','Shipment changed concurrently');const result=this.repo.getShipmentByFulfillmentId(id)!;this.repo.appendFulfillmentEvent(this.event(id,`SHIPMENT:${shipmentStatus}->${to}`,f.status,f.status,actor,operationKey,result.updatedAt));return result;});}
  handleDiscoveryBoxShortage(id:string,shortage:{originalTeaId:string;originalLotId?:string;reason:string},actor:string,operationKey:string){return this.repo.transaction(()=>{const f=this.require(id);if(f.status!=='PENDING')throw new ApplicationError('DOMAIN_RULE_VIOLATION','Discovery Box shortage can only be raised from PENDING');const items=this.repo.listFulfillmentItems(id);if(!items.some(i=>i.provenanceReference?.includes(shortage.originalTeaId)))throw new ApplicationError('DOMAIN_RULE_VIOLATION','Shortage tea is not part of this Fulfillment');const ts=now();this.repo.appendFulfillmentEvent(this.event(id,JSON.stringify({type:'DISCOVERY_BOX_SHORTAGE_PROPOSED',...shortage}),f.status,'PENDING',actor,operationKey,ts));if(!this.repo.setFulfillmentStatus(id,'PENDING','PENDING_CUSTOMER_APPROVAL',ts))throw new ApplicationError('CONFLICT','Fulfillment changed concurrently');return this.require(id);});}
  recordCustomerApproval(id:string,approval:ReplacementApproval,operationKey:string){return this.repo.transaction(()=>{const f=this.require(id);if(f.status!=='PENDING_CUSTOMER_APPROVAL')throw new ApplicationError('DOMAIN_RULE_VIOLATION','Customer approval is not currently required');if(!approval.reason.trim()||!approval.actor.trim())throw new ApplicationError('VALIDATION_ERROR','Approval reason and actor are required');const payload={type:'DISCOVERY_BOX_REPLACEMENT_DECISION',...approval};const duplicate=this.repo.listFulfillmentEvents(id).some(e=>e.eventType===JSON.stringify(payload));if(duplicate)return f;const ts=approval.timestamp||now();this.repo.appendFulfillmentEvent(this.event(id,JSON.stringify(payload),f.status,f.status,approval.actor,operationKey,ts));return this.require(id);});}
  allocateInventory(id:string,operationKey:string){return this.markReady(id,'SYSTEM',operationKey);}
  consumeInventory(id:string,operationKey:string){return this.markPacked(id,'SYSTEM',operationKey);}
  releaseInventory(id:string,operationKey:string){return this.repo.transaction(()=>{const f=this.require(id);this.release(f);this.repo.appendFulfillmentEvent(this.event(id,'INVENTORY_RELEASED',f.status,f.status,'SYSTEM',operationKey,now()));return this.require(id);});}
  private makeReady(f:FulfillmentRecord){const readiness=this.readiness(f);if(!readiness.ready){if(readiness.shortages.length)throw new ApplicationError('INSUFFICIENT_INVENTORY',`Insufficient inventory: ${readiness.shortages.join(', ')}`);throw new ApplicationError('DOMAIN_RULE_VIOLATION','Fulfillment is not ready');}const items=this.repo.listFulfillmentItems(f.id);const replacements=this.approvedReplacements(f.id);const ts=now();for(const item of items){const oi=JSON.parse(item.productSnapshotJson) as OrderItemSnapshot;const components=oi.discoveryBoxSnapshot?.items.map(x=>({teaId:x.teaId,quantity:item.quantity}))??[{teaId:oi.teaId,quantity:item.quantity}];for(const component of components){const replacement=replacements.find(r=>r.originalTeaId===component.teaId);const targetTeaId=replacement?.replacementTeaId??component.teaId;let remaining=component.quantity;const lots=this.repo.listLotsForTea(targetTeaId!).filter(l=>l.supplyStatus!=='unavailable'&&l.supplyStatus!=='discontinued');for(const lot of (replacement?.replacementLotId?lots.sort((a,b)=>a.id===replacement.replacementLotId?-1:b.id===replacement.replacementLotId?1:0):lots)){if(remaining<=0)break;const q=Math.min(remaining,lot.inventoryQuantity);if(q>0&&this.repo.decrementLotInventory(lot.id,q)){this.repo.createInventoryAllocation({id:randomUUID(),fulfillmentItemId:item.id,teaLotId:lot.id,quantity:q,status:'RESERVED',allocatedAt:ts,createdAt:ts,updatedAt:ts});remaining-=q;}}if(remaining>0)throw new ApplicationError('INSUFFICIENT_INVENTORY',`Allocation failed for tea ${targetTeaId}`);this.repo.setFulfillmentItemAllocationStatus(item.id,'ALLOCATED',ts);}}}
  private consume(f:FulfillmentRecord){const ts=now();for(const item of this.repo.listFulfillmentItems(f.id)){const allocations=this.repo.listInventoryAllocations(item.id);if(!allocations.length)throw new ApplicationError('DOMAIN_RULE_VIOLATION','Cannot mark PACKED without allocated inventory');for(const a of allocations.filter(x=>x.status==='RESERVED'))if(!this.repo.updateInventoryAllocationStatus(a.id,'RESERVED','CONSUMED',ts))throw new ApplicationError('CONFLICT','Inventory allocation changed concurrently');this.repo.setFulfillmentItemAllocationStatus(item.id,'CONSUMED',ts);}}
  private release(f:FulfillmentRecord){if(['PACKED','SHIPPED','DELIVERED','RETURNED'].includes(f.status))throw new ApplicationError('DOMAIN_RULE_VIOLATION','Consumed inventory cannot be released through cancellation');const ts=now();for(const item of this.repo.listFulfillmentItems(f.id)){for(const a of this.repo.listInventoryAllocations(item.id)){if(a.status==='RESERVED'){if(!this.repo.incrementLotInventory(a.teaLotId,a.quantity))throw new ApplicationError('CONFLICT','Inventory release failed');if(!this.repo.updateInventoryAllocationStatus(a.id,'RESERVED','RELEASED',ts))throw new ApplicationError('CONFLICT','Inventory allocation changed concurrently');}}if(item.allocationStatus==='ALLOCATED')this.repo.setFulfillmentItemAllocationStatus(item.id,'RELEASED',ts);}}
  private readiness(f:FulfillmentRecord){if(f.status!=='PENDING'&&f.status!=='PENDING_CUSTOMER_APPROVAL')return{ready:f.status==='READY',shortages:[]};const items=this.repo.listFulfillmentItems(f.id);const replacements=this.approvedReplacements(f.id);const shortages:string[]=[];for(const item of items){const oi=JSON.parse(item.productSnapshotJson) as OrderItemSnapshot;const comps=oi.discoveryBoxSnapshot?.items.map(x=>({teaId:x.teaId,quantity:item.quantity}))??[{teaId:oi.teaId,quantity:item.quantity}];for(const c of comps){const r=replacements.find(x=>x.originalTeaId===c.teaId);const tea=r?.replacementTeaId??c.teaId;if(!tea){shortages.push(item.sku);continue;}const available=this.repo.listLotsForTea(tea).filter(l=>l.supplyStatus!=='unavailable'&&l.supplyStatus!=='discontinued').reduce((s,l)=>s+l.inventoryQuantity,0);if(available<c.quantity)shortages.push(`${tea}:${c.quantity}`);}}return{ready:shortages.length===0&&(f.status==='PENDING'||(f.status==='PENDING_CUSTOMER_APPROVAL'&&replacements.length>0)),shortages};}
  private approvedReplacements(id:string){return this.repo.listFulfillmentEvents(id).map(e=>{try{return JSON.parse(e.eventType) as {type:string;originalTeaId:string;replacementTeaId:string;replacementLotId?:string;customerDecision:string}}catch{return undefined}}).filter((e):e is {type:string;originalTeaId:string;replacementTeaId:string;replacementLotId?:string;customerDecision:string}=>Boolean(e&&e.type==='DISCOVERY_BOX_REPLACEMENT_DECISION'&&e.customerDecision==='APPROVED'));}
  private exception(id:string,to:Extract<FulfillmentStatus,'FAILED'|'LOST'|'CANCELLED'|'RETURNED'>,actor:string,reason:string,operationKey:string){return this.repo.transaction(()=>{const f=this.require(id);const key=eventKey(id,operationKey);if(this.repo.listFulfillmentEvents(id).some(e=>e.eventKey===key))return f;domainGuard(()=>assertFulfillmentTransition(f.status,to));if(to==='CANCELLED'||(to==='FAILED'&&['READY','PACKING','PENDING_CUSTOMER_APPROVAL'].includes(f.status)))this.release(f);const ts=now();if(!this.repo.setFulfillmentStatus(id,f.status,to,ts))throw new ApplicationError('CONFLICT','Fulfillment changed concurrently');const result=this.require(id);this.repo.appendFulfillmentEvent(this.event(id,JSON.stringify({type:'EXCEPTION',reason}),f.status,to,actor,operationKey,ts));return result;});}
  private require(id:string){const f=this.repo.getFulfillmentById(id);if(!f)throw new ApplicationError('NOT_FOUND',`Fulfillment ${id} was not found`);return f;}
  private event(id:string,type:string,from:string|undefined,to:string|undefined,actor:string,key:string,ts:string):FulfillmentEventRecord{return{id:randomUUID(),fulfillmentId:id,eventType:type,fromStatus:from,toStatus:to,actor,occurredAt:ts,eventKey:eventKey(id,key),createdAt:ts};}
  private requireActor(actor:string){if(!actor.trim())throw new ApplicationError('VALIDATION_ERROR','Execution actor is required');}
  private requireYunela(actor:string){if(!actor.startsWith('YUNELA:')&&!actor.startsWith('SYSTEM'))throw new ApplicationError('DOMAIN_RULE_VIOLATION','YUNELA-controlled operation required');}
}
