import Database from 'better-sqlite3';
import { createMoney, type Order, type Purchase, type ShippingDetails } from '../../contracts/commerce';
import type { PaymentAttempt } from '../../contracts/payment';
import type { FulfillmentStatus, ShipmentStatus } from '../../domain/fulfillment';
import type { FulfillmentRecord, FulfillmentItemRecord, InventoryAllocationRecord, ShipmentRecord, FulfillmentEventRecord } from './repositories';
import { isApplicationError, toPersistenceError } from '../errors';

export interface PurchaseExecutionContext { purchase: Purchase; order: Order; paymentAttempt: PaymentAttempt; }
export interface FulfillmentMutationRepository {
  transaction<T>(fn: () => T): T;
  getPurchaseContext(purchaseId: string): PurchaseExecutionContext | undefined;
  getFulfillmentByPurchaseId(purchaseId: string): FulfillmentRecord | undefined;
  getFulfillmentById(id: string): FulfillmentRecord | undefined;
  listFulfillmentItems(fulfillmentId: string): FulfillmentItemRecord[];
  listInventoryAllocations(fulfillmentItemId: string): InventoryAllocationRecord[];
  createFulfillment(record: FulfillmentRecord): void;
  createFulfillmentItem(record: FulfillmentItemRecord): void;
  setFulfillmentStatus(id: string, from: FulfillmentStatus, to: FulfillmentStatus, now: string): boolean;
  setFulfillmentItemAllocationStatus(fulfillmentItemId: string, status: FulfillmentItemRecord['allocationStatus'], now: string): void;
  listLotsForTea(teaId: string): Array<{ id: string; inventoryQuantity: number; supplyStatus: string }>;
  decrementLotInventory(teaLotId: string, quantity: number): boolean;
  incrementLotInventory(teaLotId: string, quantity: number): boolean;
  createInventoryAllocation(record: InventoryAllocationRecord): void;
  updateInventoryAllocationStatus(id: string, from: InventoryAllocationRecord['status'], to: InventoryAllocationRecord['status'], now: string): boolean;
  createShipment(record: ShipmentRecord): void;
  getShipmentByFulfillmentId(fulfillmentId: string): ShipmentRecord | undefined;
  updateShipmentStatus(id: string, from: ShipmentStatus, to: ShipmentStatus, now: string): boolean;
  appendFulfillmentEvent(record: FulfillmentEventRecord): boolean;
  listFulfillmentEvents(fulfillmentId: string): FulfillmentEventRecord[];
}

function withPersistence<T>(fn: () => T): T { try { return fn(); } catch (e) { if (isApplicationError(e)) throw e; throw toPersistenceError(e); } }
function mapOrder(db: Database.Database, row: Record<string, unknown>): Order {
  const items = db.prepare('SELECT id, sku, tea_id, tea_name_snapshot, quantity, unit_price_amount, unit_price_currency, line_total_amount, recommendation_history_id, discovery_box_snapshot_json FROM order_items WHERE order_id = ? ORDER BY rowid').all(String(row.id)) as Array<Record<string, unknown>>;
  return { id:String(row.id), customerId:String(row.customer_id), status:row.status as Order['status'], items:items.map(i=>({id:String(i.id),sku:String(i.sku),...(i.tea_id?{teaId:String(i.tea_id)}:{}),teaName:String(i.tea_name_snapshot),quantity:Number(i.quantity),unitPrice:createMoney(Number(i.unit_price_amount),String(i.unit_price_currency)),lineTotal:createMoney(Number(i.line_total_amount),String(i.unit_price_currency)),...(i.recommendation_history_id?{recommendationHistoryId:String(i.recommendation_history_id)}:{}),...(i.discovery_box_snapshot_json?{discoveryBoxSnapshot:JSON.parse(String(i.discovery_box_snapshot_json))}: {})})),pricingSnapshot:{subtotal:createMoney(Number(row.subtotal_amount),String(row.currency)),discounts:createMoney(Number(row.discount_amount),String(row.currency)),shipping:createMoney(Number(row.shipping_amount),String(row.currency)),total:createMoney(Number(row.total_amount),String(row.currency))},shipping:JSON.parse(String(row.shipping_snapshot_json)) as ShippingDetails,createdAt:String(row.created_at),updatedAt:String(row.updated_at)};
}
function mapPurchase(row: Record<string, unknown>): Purchase { return { id:String(row.id),orderId:String(row.order_id),customerId:String(row.customer_id),amount:createMoney(Number(row.amount),String(row.currency)),confirmedAt:String(row.confirmed_at),...(row.payment_attempt_id?{paymentAttemptId:String(row.payment_attempt_id)}:{}),...(row.provider?{provider:'MONO' as const}:{}),...(row.provider_invoice_id?{providerInvoiceId:String(row.provider_invoice_id)}:{}),...(row.provider_reference?{providerReference:String(row.provider_reference)}:{})}; }
function mapAttempt(row: Record<string, unknown>): PaymentAttempt { return { id:String(row.id),orderId:String(row.order_id),customerId:String(row.customer_id),provider:'MONO',...(row.provider_invoice_id?{providerInvoiceId:String(row.provider_invoice_id)}:{}),merchantReference:String(row.merchant_reference),requestedAmount:createMoney(Number(row.requested_amount),'UAH'),requestedCurrency:'UAH',state:row.state as PaymentAttempt['state'],...(row.provider_status?{providerStatus:String(row.provider_status)}:{}),...(row.provider_modified_at?{providerModifiedAt:String(row.provider_modified_at)}:{}),...(row.provider_event_fingerprint?{providerEventFingerprint:String(row.provider_event_fingerprint)}:{}),...(row.provider_event_reference?{providerEventReference:String(row.provider_event_reference)}:{}),idempotencyKey:String(row.idempotency_key),...(row.payment_page_url?{paymentPageUrl:String(row.payment_page_url)}:{}),createdAt:String(row.created_at),updatedAt:String(row.updated_at),...(row.confirmed_at?{confirmedAt:String(row.confirmed_at)}:{})}; }
function mapFulfillment(row: Record<string, unknown>): FulfillmentRecord { return {id:String(row.id),orderId:String(row.order_id),purchaseId:String(row.purchase_id),customerId:String(row.customer_id),status:row.status as FulfillmentStatus,shippingSnapshotJson:String(row.shipping_snapshot_json),itemsSnapshotJson:String(row.items_snapshot_json),...(row.failure_code?{failureCode:String(row.failure_code)}:{}),...(row.failure_reason?{failureReason:String(row.failure_reason)}:{}),createdAt:String(row.created_at),updatedAt:String(row.updated_at)}; }
function mapItem(row: Record<string, unknown>): FulfillmentItemRecord { return {id:String(row.id),fulfillmentId:String(row.fulfillment_id),orderItemId:String(row.order_item_id),sku:String(row.sku),quantity:Number(row.quantity),productSnapshotJson:String(row.product_snapshot_json),...(row.provenance_reference?{provenanceReference:String(row.provenance_reference)}:{}),allocationStatus:row.allocation_status as FulfillmentItemRecord['allocationStatus'],createdAt:String(row.created_at),updatedAt:String(row.updated_at)}; }
function mapAlloc(row: Record<string, unknown>): InventoryAllocationRecord { return {id:String(row.id),fulfillmentItemId:String(row.fulfillment_item_id),teaLotId:String(row.tea_lot_id),quantity:Number(row.quantity),status:row.status as InventoryAllocationRecord['status'],...(row.allocated_at?{allocatedAt:String(row.allocated_at)}:{}),...(row.consumed_at?{consumedAt:String(row.consumed_at)}:{}),...(row.released_at?{releasedAt:String(row.released_at)}:{}),createdAt:String(row.created_at),updatedAt:String(row.updated_at)}; }
function mapShipment(row: Record<string, unknown>): ShipmentRecord { return {id:String(row.id),fulfillmentId:String(row.fulfillment_id),status:String(row.status),...(row.carrier?{carrier:String(row.carrier)}:{}),...(row.tracking_number?{trackingNumber:String(row.tracking_number)}:{}),...(row.tracking_url?{trackingUrl:String(row.tracking_url)}:{}),...(row.shipped_at?{shippedAt:String(row.shipped_at)}:{}),...(row.delivered_at?{deliveredAt:String(row.delivered_at)}:{}),createdAt:String(row.created_at),updatedAt:String(row.updated_at)}; }
function mapEvent(row: Record<string, unknown>): FulfillmentEventRecord { return {id:String(row.id),fulfillmentId:String(row.fulfillment_id),eventType:String(row.event_type),...(row.from_status?{fromStatus:String(row.from_status)}:{}),...(row.to_status?{toStatus:String(row.to_status)}:{}),actor:String(row.actor),occurredAt:String(row.occurred_at),eventKey:String(row.event_key),createdAt:String(row.created_at)}; }

export class SqliteFulfillmentMutationRepository implements FulfillmentMutationRepository {
  constructor(private readonly db: Database.Database) {}
  transaction<T>(fn: () => T): T { return this.db.transaction(fn)(); }
  getPurchaseContext(purchaseId:string): PurchaseExecutionContext|undefined { return withPersistence(()=>{const p=this.db.prepare('SELECT * FROM purchases WHERE id=?').get(purchaseId) as Record<string,unknown>|undefined;if(!p)return undefined;const orderRow=this.db.prepare('SELECT * FROM orders WHERE id=?').get(String(p.order_id)) as Record<string,unknown>|undefined;if(!orderRow)return undefined;const purchase=mapPurchase(p);const a=p.payment_attempt_id?this.db.prepare('SELECT * FROM payment_attempts WHERE id=?').get(String(p.payment_attempt_id)) as Record<string,unknown>|undefined:this.db.prepare("SELECT * FROM payment_attempts WHERE order_id=? AND state='SUCCEEDED' ORDER BY confirmed_at DESC,id DESC LIMIT 1").get(String(p.order_id)) as Record<string,unknown>|undefined;if(!a)return undefined;return {purchase,order:mapOrder(this.db,orderRow),paymentAttempt:mapAttempt(a)};}); }
  getFulfillmentByPurchaseId(purchaseId:string){return withPersistence(()=>{const r=this.db.prepare('SELECT * FROM fulfillments WHERE purchase_id=?').get(purchaseId) as Record<string,unknown>|undefined;return r?mapFulfillment(r):undefined;});}
  getFulfillmentById(id:string){return withPersistence(()=>{const r=this.db.prepare('SELECT * FROM fulfillments WHERE id=?').get(id) as Record<string,unknown>|undefined;return r?mapFulfillment(r):undefined;});}
  listFulfillmentItems(id:string){return withPersistence(()=> (this.db.prepare('SELECT * FROM fulfillment_items WHERE fulfillment_id=? ORDER BY created_at,id').all(id) as Array<Record<string,unknown>>).map(mapItem));}
  listInventoryAllocations(id:string){return withPersistence(()=> (this.db.prepare('SELECT * FROM inventory_allocations WHERE fulfillment_item_id=? ORDER BY created_at,id').all(id) as Array<Record<string,unknown>>).map(mapAlloc));}
  createFulfillment(r:FulfillmentRecord){this.db.prepare('INSERT INTO fulfillments (id,order_id,purchase_id,customer_id,status,shipping_snapshot_json,items_snapshot_json,failure_code,failure_reason,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)').run(r.id,r.orderId,r.purchaseId,r.customerId,r.status,r.shippingSnapshotJson,r.itemsSnapshotJson,r.failureCode??null,r.failureReason??null,r.createdAt,r.updatedAt);}
  createFulfillmentItem(r:FulfillmentItemRecord){this.db.prepare('INSERT INTO fulfillment_items (id,fulfillment_id,order_item_id,sku,quantity,product_snapshot_json,provenance_reference,allocation_status,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?)').run(r.id,r.fulfillmentId,r.orderItemId,r.sku,r.quantity,r.productSnapshotJson,r.provenanceReference??null,r.allocationStatus,r.createdAt,r.updatedAt);}
  setFulfillmentStatus(id:string,from:FulfillmentStatus,to:FulfillmentStatus,now:string){return this.db.prepare('UPDATE fulfillments SET status=?,updated_at=? WHERE id=? AND status=?').run(to,now,id,from).changes===1;}
  setFulfillmentItemAllocationStatus(id:string,status:FulfillmentItemRecord['allocationStatus'],now:string){this.db.prepare('UPDATE fulfillment_items SET allocation_status=?,updated_at=? WHERE id=?').run(status,now,id);}
  listLotsForTea(teaId:string){return (this.db.prepare("SELECT id,inventory_quantity,supply_status FROM tea_lots WHERE tea_id=? AND inventory_quantity>0 ORDER BY created_at,id").all(teaId) as Array<Record<string,unknown>>).map(r=>({id:String(r.id),inventoryQuantity:Number(r.inventory_quantity),supplyStatus:String(r.supply_status)}));}
  decrementLotInventory(id:string,q:number){return this.db.prepare('UPDATE tea_lots SET inventory_quantity=inventory_quantity-?,updated_at=? WHERE id=? AND inventory_quantity>=?').run(q,new Date().toISOString(),id,q).changes===1;}
  incrementLotInventory(id:string,q:number){return this.db.prepare('UPDATE tea_lots SET inventory_quantity=inventory_quantity+?,updated_at=? WHERE id=?').run(q,new Date().toISOString(),id).changes===1;}
  createInventoryAllocation(r:InventoryAllocationRecord){this.db.prepare('INSERT INTO inventory_allocations (id,fulfillment_item_id,tea_lot_id,quantity,status,allocated_at,consumed_at,released_at,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?)').run(r.id,r.fulfillmentItemId,r.teaLotId,r.quantity,r.status,r.allocatedAt??null,r.consumedAt??null,r.releasedAt??null,r.createdAt,r.updatedAt);}
  updateInventoryAllocationStatus(id:string,from:InventoryAllocationRecord['status'],to:InventoryAllocationRecord['status'],now:string){const fields=to==='CONSUMED'?'consumed_at=?':to==='RELEASED'?'released_at=?':'allocated_at=?';return this.db.prepare(`UPDATE inventory_allocations SET status=?,${fields},updated_at=? WHERE id=? AND status=?`).run(to,now,now,id,from).changes===1;}
  createShipment(r:ShipmentRecord){this.db.prepare('INSERT INTO shipments (id,fulfillment_id,status,carrier,tracking_number,tracking_url,shipped_at,delivered_at,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?)').run(r.id,r.fulfillmentId,r.status,r.carrier??null,r.trackingNumber??null,r.trackingUrl??null,r.shippedAt??null,r.deliveredAt??null,r.createdAt,r.updatedAt);}
  getShipmentByFulfillmentId(id:string){return withPersistence(()=>{const r=this.db.prepare('SELECT * FROM shipments WHERE fulfillment_id=?').get(id) as Record<string,unknown>|undefined;return r?mapShipment(r):undefined;});}
  updateShipmentStatus(id:string,from:ShipmentStatus,to:ShipmentStatus,now:string){const shipped=to==='SHIPPED'?now:null,delivered=to==='DELIVERED'?now:null;return this.db.prepare('UPDATE shipments SET status=?,shipped_at=COALESCE(?,shipped_at),delivered_at=COALESCE(?,delivered_at),updated_at=? WHERE id=? AND status=?').run(to,shipped,delivered,now,id,from).changes===1;}
  appendFulfillmentEvent(r:FulfillmentEventRecord){try{this.db.prepare('INSERT INTO fulfillment_events (id,fulfillment_id,event_type,from_status,to_status,actor,occurred_at,event_key,created_at) VALUES (?,?,?,?,?,?,?,?,?)').run(r.id,r.fulfillmentId,r.eventType,r.fromStatus??null,r.toStatus??null,r.actor,r.occurredAt,r.eventKey,r.createdAt);return true;}catch(e){if(String(e).includes('UNIQUE'))return false;throw e;}}
  listFulfillmentEvents(id:string){return withPersistence(()=> (this.db.prepare('SELECT * FROM fulfillment_events WHERE fulfillment_id=? ORDER BY occurred_at,id').all(id) as Array<Record<string,unknown>>).map(mapEvent));}
}
