import { randomUUID } from 'node:crypto';
import type { AnalyticsTracker } from '../../contracts/analytics';
import type { Cart, CartItem, CreateOrderRequest, DiscoveryBoxSnapshot, Money, Order, OrderItemSnapshot, Purchase } from '../../contracts/commerce';
import { createMoney } from '../../contracts/commerce';
import type { CommercialProductRepository } from '../../contracts/catalog';
import type { CustomerRepository, DiscoveryBoxRepository, RecommendationHistoryRepository, TeaRepository } from '../repositories';
import type { CartRepository, OrderRepository, PurchaseRepository } from './repositories';
import { ApplicationError } from '../errors';

const CURRENCY = 'UAH';
const ZERO = () => createMoney(0, CURRENCY);
function assertCustomer(customerRepository: CustomerRepository, customerId: string): void { if (!customerRepository.getById(customerId)) throw new ApplicationError('NOT_FOUND', `Customer ${customerId} was not found`); }
function assertQuantity(quantity: number): void { if (!Number.isInteger(quantity) || quantity <= 0) throw new ApplicationError('INVALID_QUANTITY', 'quantity must be a positive integer'); }
function assertSku(sku: string): void { if (!sku.trim() || sku.length > 128) throw new ApplicationError('INVALID_SKU', 'sku is invalid'); }

export class CartService {
  constructor(private readonly carts: CartRepository, private readonly products: CommercialProductRepository, private readonly teas: TeaRepository, private readonly customers: CustomerRepository, private readonly boxes: DiscoveryBoxRepository, private readonly recommendationHistory: RecommendationHistoryRepository, private readonly analytics: AnalyticsTracker) {}
  createCart(customerId: string): Cart { assertCustomer(this.customers, customerId); const existing = this.carts.getByCustomerId(customerId); if (existing) return this.refresh(existing, customerId); const now = new Date().toISOString(); const cart: Cart = { id: randomUUID(), customerId, items: [], subtotal: ZERO(), discounts: ZERO(), total: ZERO(), createdAt: now, updatedAt: now }; this.carts.create(cart); return cart; }
  getCart(customerId: string, cartId: string): Cart { return this.refresh(this.requireOwned(customerId, cartId), customerId); }
  addItem(customerId: string, cartId: string, input: { sku: string; quantity: number; recommendationHistoryId?: string; discoveryBoxId?: string }): Cart {
    assertQuantity(input.quantity); assertSku(input.sku); const cart = this.requireOwned(customerId, cartId); const product = this.resolveProduct(input.sku); this.validateProduct(product.sku, product.kind, product.available, product.teaId, product.discoveryBoxId, input.discoveryBoxId, customerId);
    if (input.recommendationHistoryId) { const history = this.recommendationHistory.getById(input.recommendationHistoryId); if (!history || history.customerId !== customerId || (product.teaId && history.teaId !== product.teaId)) throw new ApplicationError('DOMAIN_RULE_VIOLATION', 'Recommendation provenance is invalid'); }
    const existing = cart.items.find((item) => item.sku === input.sku); const quantity = (existing?.quantity ?? 0) + input.quantity; this.validateInventory(product.teaId, quantity);
    const item: CartItem = { id: existing?.id ?? randomUUID(), sku: product.sku, ...(product.teaId ? { teaId: product.teaId } : {}), quantity, unitPrice: product.price, ...(input.recommendationHistoryId ? { recommendationHistoryId: input.recommendationHistoryId } : existing?.recommendationHistoryId ? { recommendationHistoryId: existing.recommendationHistoryId } : {}), ...(product.discoveryBoxId ? { discoveryBoxId: product.discoveryBoxId } : existing?.discoveryBoxId ? { discoveryBoxId: existing.discoveryBoxId } : {}) };
    cart.items = existing ? cart.items.map((value) => value.sku === item.sku ? item : value) : [...cart.items, item]; this.persist(cart); this.analytics.track('add_to_cart', { customerId, cartId, sku: product.sku, quantity: input.quantity }); return cart;
  }
  updateItem(customerId: string, cartId: string, sku: string, quantity: number): Cart { assertQuantity(quantity); assertSku(sku); const cart = this.requireOwned(customerId, cartId); const item = cart.items.find((value) => value.sku === sku); if (!item) throw new ApplicationError('CART_ITEM_NOT_FOUND', `Cart item ${sku} was not found`); const product = this.resolveProduct(sku); this.validateProduct(product.sku, product.kind, product.available, product.teaId, product.discoveryBoxId, item.discoveryBoxId, customerId); this.validateInventory(product.teaId, quantity); cart.items = cart.items.map((value) => value.sku === sku ? { ...value, quantity, unitPrice: product.price } : value); this.persist(cart); return cart; }
  removeItem(customerId: string, cartId: string, sku: string): Cart { assertSku(sku); const cart = this.requireOwned(customerId, cartId); if (!cart.items.some((value) => value.sku === sku)) throw new ApplicationError('CART_ITEM_NOT_FOUND', `Cart item ${sku} was not found`); cart.items = cart.items.filter((value) => value.sku !== sku); this.persist(cart); return cart; }
  private requireOwned(customerId: string, cartId: string): Cart { const cart = this.carts.getById(cartId); if (!cart) throw new ApplicationError('CART_NOT_FOUND', `Cart ${cartId} was not found`); if (cart.customerId !== customerId) throw new ApplicationError('CART_NOT_OWNED', `Cart ${cartId} is not owned by customer ${customerId}`); return cart; }
  private resolveProduct(sku: string) { const product = this.products.getBySku(sku); if (!product) throw new ApplicationError('PRODUCT_NOT_FOUND', `Commercial product ${sku} was not found`); if (product.price.currency !== CURRENCY) throw new ApplicationError('INVALID_CURRENCY', 'D2 supports UAH only'); return product; }
  private validateProduct(sku: string, kind: string, available: boolean, teaId: string | undefined, boxId: string | undefined, requestedBoxId: string | undefined, customerId: string): void { if (!available) throw new ApplicationError('PRODUCT_UNAVAILABLE', `Product ${sku} is unavailable`); if (kind === 'TEA' && !teaId) throw new ApplicationError('DOMAIN_RULE_VIOLATION', `Tea product ${sku} has no tea identity`); if (kind === 'DISCOVERY_BOX') { if (!boxId || requestedBoxId !== boxId) throw new ApplicationError('DOMAIN_RULE_VIOLATION', 'Discovery Box provenance is required for a Discovery Box SKU'); const box = this.boxes.getById(boxId); if (!box || box.customerId !== customerId) throw new ApplicationError('DOMAIN_RULE_VIOLATION', 'Discovery Box is not owned by the customer'); if (box.items.length !== 6) throw new ApplicationError('DOMAIN_RULE_VIOLATION', 'Discovery Box composition must contain six teas'); } }
  private validateInventory(teaId: string | undefined, quantity: number): void { if (!teaId) return; const tea = this.teas.getById(teaId); if (!tea) throw new ApplicationError('PRODUCT_NOT_FOUND', `Tea ${teaId} was not found`); if (tea.inventory < quantity) throw new ApplicationError('INSUFFICIENT_INVENTORY', `Insufficient inventory for tea ${teaId}`); if (tea.publishingState !== 'published' || tea.supplyStatus === 'unavailable' || tea.supplyStatus === 'discontinued') throw new ApplicationError('PRODUCT_UNAVAILABLE', `Tea ${teaId} is unavailable`); }
  private refresh(cart: Cart, customerId: string): Cart { cart.items = cart.items.map((item) => { const product = this.resolveProduct(item.sku); if (product.kind === 'TEA') this.validateProduct(product.sku, product.kind, product.available, product.teaId, product.discoveryBoxId, item.discoveryBoxId, customerId); return { ...item, ...(product.teaId ? { teaId: product.teaId } : {}), unitPrice: product.price }; }); this.reprice(cart); this.carts.save(cart); return cart; }
  private persist(cart: Cart): void { this.reprice(cart); cart.updatedAt = new Date().toISOString(); this.carts.save(cart); }
  private reprice(cart: Cart): void { const subtotal = cart.items.reduce((sum, item) => sum + item.unitPrice.amount * item.quantity, 0); cart.subtotal = createMoney(subtotal, CURRENCY); cart.discounts = ZERO(); cart.total = createMoney(subtotal, CURRENCY); }
}

export class OrderService {
  constructor(private readonly orders: OrderRepository, private readonly carts: CartRepository, private readonly products: CommercialProductRepository, private readonly teas: TeaRepository, private readonly boxes: DiscoveryBoxRepository, private readonly customers: CustomerRepository, private readonly analytics: AnalyticsTracker) {}
  createOrder(customerId: string, request: CreateOrderRequest): Order {
    assertCustomer(this.customers, customerId); if (!request.idempotencyKey.trim()) throw new ApplicationError('VALIDATION_ERROR', 'idempotencyKey is required'); const existing = this.orders.getByIdempotency(customerId, request.idempotencyKey); if (existing) return existing;
    const cart = this.carts.getById(request.cartId); if (!cart) throw new ApplicationError('CART_NOT_FOUND', `Cart ${request.cartId} was not found`); if (cart.customerId !== customerId) throw new ApplicationError('CART_NOT_OWNED', `Cart ${request.cartId} is not owned by customer ${customerId}`); if (cart.items.length === 0) throw new ApplicationError('DOMAIN_RULE_VIOLATION', 'Cannot create an Order from an empty Cart');
    const items: OrderItemSnapshot[] = cart.items.map((cartItem) => { const product = this.products.getBySku(cartItem.sku); if (!product) throw new ApplicationError('PRODUCT_NOT_FOUND', `Commercial product ${cartItem.sku} was not found`); if (!product.available) throw new ApplicationError('PRODUCT_UNAVAILABLE', `Product ${cartItem.sku} is unavailable`); if (product.price.currency !== CURRENCY) throw new ApplicationError('INVALID_CURRENCY', 'D2 supports UAH only');
      if (product.kind === 'TEA') { if (!product.teaId) throw new ApplicationError('DOMAIN_RULE_VIOLATION', `Tea product ${product.sku} has no tea identity`); const tea = this.teas.getById(product.teaId); if (!tea) throw new ApplicationError('PRODUCT_NOT_FOUND', `Tea ${product.teaId} was not found`); if (tea.publishingState !== 'published' || tea.supplyStatus === 'unavailable' || tea.supplyStatus === 'discontinued') throw new ApplicationError('PRODUCT_UNAVAILABLE', `Tea ${product.teaId} is unavailable`); if (tea.inventory < cartItem.quantity) throw new ApplicationError('INSUFFICIENT_INVENTORY', `Insufficient inventory for tea ${product.teaId}`); return { id: randomUUID(), sku: product.sku, teaId: product.teaId, teaName: tea.name, quantity: cartItem.quantity, unitPrice: product.price, lineTotal: createMoney(product.price.amount * cartItem.quantity, CURRENCY), ...(cartItem.recommendationHistoryId ? { recommendationHistoryId: cartItem.recommendationHistoryId } : {}) }; }
      if (!product.discoveryBoxId) throw new ApplicationError('DOMAIN_RULE_VIOLATION', `Discovery Box product ${product.sku} has no originating box`); const box = this.boxes.getById(product.discoveryBoxId); if (!box || box.items.length !== 6) throw new ApplicationError('PRODUCT_UNAVAILABLE', `Discovery Box ${product.discoveryBoxId} is unavailable`); const snapshot: DiscoveryBoxSnapshot = { discoveryBoxId: box.id, algorithmVersion: box.algorithmVersion, selectionVersion: box.selectionVersion, items: box.items.map((item) => { const tea = this.teas.getById(item.teaId); if (!tea) throw new ApplicationError('PRODUCT_NOT_FOUND', `Tea ${item.teaId} was not found`); return { teaId: item.teaId, teaName: tea.name, classification: item.classification, position: item.position, score: item.score, reasons: [...item.reasons] }; }) }; return { id: randomUUID(), sku: product.sku, quantity: cartItem.quantity, teaName: product.name, unitPrice: product.price, lineTotal: createMoney(product.price.amount * cartItem.quantity, CURRENCY), discoveryBoxSnapshot: snapshot };
    });
    const subtotal = createMoney(items.reduce((sum, item) => sum + item.lineTotal.amount, 0), CURRENCY); const order: Order = { id: randomUUID(), customerId, status: 'created', items, pricingSnapshot: { subtotal, discounts: ZERO(), shipping: ZERO(), total: subtotal }, shipping: request.shipping, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }; this.orders.create(order, request.idempotencyKey); this.analytics.track('order_created', { customerId, orderId: order.id, cartId: request.cartId, total: order.pricingSnapshot.total.amount }); return order;
  }
  getOrder(customerId: string, orderId: string): Order { const order = this.orders.getById(orderId); if (!order) throw new ApplicationError('ORDER_NOT_FOUND', `Order ${orderId} was not found`); if (order.customerId !== customerId) throw new ApplicationError('ORDER_NOT_OWNED', `Order ${orderId} is not owned by customer ${customerId}`); return order; }
}

export interface AuthoritativePaymentConfirmation { orderId: string; customerId: string; amount: Money; confirmedAt: string; }
export class PurchaseBoundaryService {
  constructor(private readonly purchases: PurchaseRepository, private readonly orders: OrderRepository, private readonly analytics: AnalyticsTracker) {}
  recordAuthoritativePurchase(input: AuthoritativePaymentConfirmation): Purchase { const order = this.orders.getById(input.orderId); if (!order || order.customerId !== input.customerId) throw new ApplicationError('PURCHASE_NOT_AUTHORIZED', 'Order is not available for purchase confirmation'); if (input.amount.currency !== CURRENCY || input.amount.amount !== order.pricingSnapshot.total.amount) throw new ApplicationError('PURCHASE_NOT_AUTHORIZED', 'Confirmed amount does not match Order total'); const existing = this.purchases.getByOrderId(input.orderId); if (existing) return existing; const purchase: Purchase = { id: randomUUID(), orderId: order.id, customerId: order.customerId, amount: input.amount, confirmedAt: input.confirmedAt }; this.purchases.create(purchase); this.analytics.track('purchase', { customerId: purchase.customerId, orderId: purchase.orderId, amount: purchase.amount.amount }); if (order.items.some((item) => Boolean(item.discoveryBoxSnapshot))) this.analytics.track('box_purchase', { customerId: purchase.customerId, orderId: purchase.orderId }); return purchase; }
}
